/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t scene.gltf 
Author: grafi (https://sketchfab.com/zdenkoroman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stack-of-books-3d-scan-975887dad9a2474bacb9fec3850c48c5
Title: Stack of Books 3D scan
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type ActionName = 'Animation';

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
  };
  materials: {
    material_0: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function BookStack(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/book_stack/scene.glb',
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.material_0}
        position={[0, 0, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.025}
      />
    </group>
  );
}

useGLTF.preload('/models/book_stack/scene.glb');
