/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t scene.gltf 
Author: draakon_4d (https://sketchfab.com/draakon_4d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-desk-98c5bd86d7bb4ca98dbc26dabb5e7196
Title: Computer Desk
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { Bird } from './Bird';
import { degToRad } from 'three/src/math/MathUtils';

type ActionName = 'Animation';

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_14: THREE.Mesh;
  };
  materials: {
    comp_desk_c: THREE.MeshStandardMaterial;
    comp_desk: THREE.MeshStandardMaterial;
    comp_desk_b: THREE.MeshStandardMaterial;
    comp_desk_a: THREE.MeshStandardMaterial;
    comp_desk_remote: THREE.MeshStandardMaterial;
    comp_desk_2remote: THREE.MeshStandardMaterial;
    comp_desk_1remote: THREE.MeshStandardMaterial;
    comp_desk_button: THREE.MeshStandardMaterial;
    comp_desk_top: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Desk(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/computer_desk/scene.glb',
  ) as GLTFResult;
  return (
    <group {...props} scale={[7, 7, 7]} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.comp_desk_c}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.comp_desk}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.comp_desk_b}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.comp_desk_a}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.comp_desk_remote}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.comp_desk_2remote}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.comp_desk_1remote}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.comp_desk_button}
        />
      </group>
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.comp_desk_top}
      />

      {/* Add desk objects */}
    </group>
  );
}

useGLTF.preload('/models/computer_desk/scene.glb');
